BUILD-2293: Migrate to Vault
SonarSource/sonarqube-roslyn-sdk-template-plugin pull request #26
Opened 2022-12-15 15:15 UTC by vlad-sonar

2022-12-15 15:34 UTC, tomverin requested changes

2022-12-15 15:34 UTC, tomverin commented on .cirrus.yml
> +  GITHUB_TOKEN: VAULT[development/github/token/licenses-ro token]
you need to move this token from here to the promote task and use the promotion path

2022-12-15 16:10 UTC, tomverin approved these changes

2022-12-16 10:32 UTC, Godin approved these changes

2022-12-16 10:33 UTC, merged

2022-12-16 12:32 UTC, Godin commented
For the record

Even if the build was green in this PR, it failed immediately after merge into `master` with the following message
```
❗ Fatal exception on the agent!

failed to initialize a Vault client: unable to log in to auth method: Error making API request.

URL: PUT https://vault.sonar.build:8200/v1/auth/jwt-cirrusci/login
Code: 400. Errors:

role "cirrusci-sonarsource-sonarqube-roslyn-sdk-template-plugin" could not be found
```
see https://cirrus-ci.com/task/6320869545869312

I suspect that the problem is not in changes of this PR, but on the Vault side and @tomverin is already aware of this and will look at this.

2022-12-16 13:48 UTC, Godin commented
For the record: fixed by https://github.com/SonarSource/re-terraform-aws-vault/commit/bfb03addb884622b3f807e436d10652ada7f9d51